### ISSUE TITLE
Time picker doesn't respect 12/24 hours locale

### ISSUE THREAD

**Issue by Andreaaa** [avjinder/Minimal-Todo#1]
The time picker always uses the AM/PM format, instead of honoring the system preference.

**Comment by Andreaaa** [comment]
You can find the code to fix this bug here: https://github.com/Andreaaa/MinimalToDo

Unfortunately, I don't know how to ask for a pull request

**Comment by avjinder** [comment]
Thanks. 24h time-picker is now available.
