### ISSUE TITLE
cannot resolve symbol libcore

### ISSUE THREAD

**Issue by 11510746** [avjinder/Minimal-Todo#108]
When I mocked the JsonObject, I find an error `cannot resolve symbol libcore`.

**Comment by umartinez22** [comment]
Hello, could you explain more about the problem?

**Comment by ghost** [comment]
> Hello, could you explain more about the problem?

I got this error when I try to run unit test. But finally I built my unit test by modified the `build.gradle` file.
```
defaultConfig {
    testInstrumentationRunner = 'android.support.test.runner.AndroidJUnitRunner'
}

dependencies {
    testImplementation 'junit:junit:4.12'
    testImplementation 'org.json:json:20140107'
}
```
I also learn When to use instrumented tests and when to use local unit tests. In this project, [the class JSONObject is part of the android SDK. That means that is not available for unit testing by default](https://stackoverflow.com/questions/32385092/why-is-my-jsonobject-related-unit-test-failing/41398830). Maybe it is better to use instrumented tests.
