### ISSUE TITLE
How do you completely disable analytics?

### ISSUE THREAD

**Issue by fnokeke** [avjinder/Minimal-Todo#14]
I'm having a lot of crashes even as I step through the code and try to remove the analytics part. Can you suggest the most minimal efforts to completely disable analytics?

Thanks

**Comment by rubenroy** [comment]
Try changing `IS_ENABLED` to `false` in [AnalyticsApplication.java:15](https://github.com/avjinder/Minimal-Todo/blob/master/app/src/main/java/com/example/avjindersinghsekhon/toodle/AnalyticsApplication.java#L15)

**Comment by fnokeke** [comment]
Thank you. I just realized it works if I added `app_tracker.xml` to `res` with a random value ` <string name="ga_trackingId">UX-XXXXXXXX-Y</string>`
