### ISSUE TITLE
Play-Service as a buildtime dependency

### ISSUE THREAD

**Issue by xfausto** [avjinder/Minimal-Todo#15]
Is it possible to provide a way to build this application without Play-Services as a buildtime dependency so it can be distributed on F-Droid? https://f-droid.org/forums/topic/minimal-todo/#post-17472

**Comment by avjinder** [comment]
I will look into it and if it's possible, I'll remove play services.

**Comment by piotrek1543** [comment]
@avjinder, you don't want to do something with this issue, please close it.

**Comment by rubenroy** [comment]
The app is now published on [fdroid] (https://f-droid.org/repository/browse/?fdid=com.rubenroy.minimaltodo)

**Comment by smichel17** [comment]
Any reason this issue is still open?
