### ISSUE TITLE
Add "Contribution" section in README.md

### ISSUE THREAD

**Issue by piotrek1543** [avjinder/Minimal-Todo#20]
Hi, I reallly like your project and I would like to help you improving it, but there's no information about terms of contribution to your project.

Please, put new section in README.md file or create a new text file to get me and other pretend to be contributors get to know how we can make it real.

Maybe this article will help you: 
http://www.erikaheidi.com/blog/is-your-open-source-project-welcoming-to-new-contributors

**Comment by rubenroy** [comment]
Send a pull request perhaps?

**Comment by piotrek1543** [comment]
Well, that's good idea. In few next days I will create new pull request with this improvement. Thanks!

**Comment by piotrek1543** [comment]
I'd made a commit to existing pull request #19

**Comment by avjinder** [comment]
Hi piotrek1543, thanks for the great contributing page.

**Comment by piotrek1543** [comment]
I'm glad I was able to help. Now I can close issue.
