### ISSUE TITLE
Group ToDos

### ISSUE THREAD

**Issue by grrrrr** [avjinder/Minimal-Todo#26]
Fantastic application and this might go against the idea of it being minimal but would it be possible to group the ToDos.

I am thinking maybe a collapsible grouping

Group 1 (expand/collapse)
  |_ todo1
  |_ todo2
Group 2 (exapnd/collapse)
  |_todo1
  |_todo2

**Comment by cuikangyuan** [comment]
aha,how about sort by  create date ? now when we add a new item , i think the sort order is confusing..

**Comment by inzkhan** [comment]
Sorting by date should be implemented .

**Comment by adiaholic** [comment]
Is this issue being worked on ?

**Comment by grrrrr** [comment]
closing as this project has not been updated in 4 years
