### ISSUE TITLE
Secure Storage for Minimal-Todo

### ISSUE THREAD

**Issue by grrrrr** [avjinder/Minimal-Todo#27]
Would it be possible to add some security features to Minimal-Todo via Guardian Projects' [SQLCipher](https://guardianproject.info/code/sqlcipher/) and [IOCipher](https://guardianproject.info/code/iocipher/)?

To users who did not want or need the feature the app would works as it does now, for those that did want it they can set a password on the app which they would be prompted for any time it was locked.

**Comment by waqas** [comment]
+1

**Comment by grrrrr** [comment]
project idle for 4 years, closing
