### ISSUE TITLE
Add a black theme

### ISSUE THREAD

**Issue by grrrrr** [avjinder/Minimal-Todo#28]
Currently there is a night mode theme which sets the background to a grey / black color.  Would it be possible to add a pure black background option to benefit those with AMOLED screens?

**Comment by smichel17** [comment]
If this is implemented, I suggest the following implementation:

"Night Mode" check box replaced with "Theme" drop down containing three options:
- Light *(current light mode)*
- Dark *(current night mode)*
- Night *(Black background, grey header, blue or lighter grey FAB)*

**Comment by grrrrr** [comment]
project idle for 4 years, closing
