### ISSUE TITLE
App crashes after deleting ToDo and still shown in NotificationBar

### ISSUE THREAD

**Issue by GuteIdee** [avjinder/Minimal-Todo#63]
For Example:
Adding new Todo with Alarm (12:50).
Alarm is showing in the NotificationBar.
Deleting the Todo.
The Alarm will NOT deleted in the NotificationBar.
OnClick on the Notification will crash the app

**Comment by raj10071997** [comment]
close this issue as the bug has been fixed.

**Comment by ghost** [comment]
This bug still exists
