### ISSUE TITLE
Copyright violation

### ISSUE THREAD

**Issue by Poussinou** [avjinder/Minimal-Todo#66]
Hi @avjinder

I found [this app](https://play.google.com/store/apps/details?id=com.ikramshah.tasklist) on the Google Play Store. This guy just took your source code, added some ads in it and put it on the Store, without warning this is free software...

As you are the owner of the source code, feel free to open a request to google [here](https://support.google.com/legal/contact/lr_dmca?product=googleplay) to remove the false app from the Store, if it's your wish ;)

Don't forget to tell Google that:

* The app is licensed under MIT license and this guy is violating it;
* He is falsely claiming he made the app;
* Also tell them that this guy has done the same thing already with other apps. Probably this is worth mentioning.

**Comment by Poussinou** [comment]
@avjinder There is also [this one](https://play.google.com/store/apps/details?id=com.andrew.ehome.app.ehometodolist)... And probably more...

Maybe you should take some time (one hour or something so) to check the other apps about "Todos" on Google Play Store, and report them to Google, when they are just like your own app. I think some apps on the Store are just your app "Minimal To Do" with ads in it, and without MIT License, code source and your permission... If you do it, please copy-paste the links of the apps you reported in this thread, so that I can track the "Google developers" who are stealing your work. Thanks

**Comment by inzkhan** [comment]
@Poussinou .Keep it .You are doing good work .

**Comment by Poussinou** [comment]
All copycats have been removed. Please report here if you find other copies 👍
