### ISSUE TITLE
Could not find method google() for arguments [] on repository container.

### ISSUE THREAD

**Issue by savked** [avjinder/Minimal-Todo#88]
Getting "Could not find method google() for arguments [] on repository container."  when Gradle Building.

**Comment by 11510746** [comment]
How to resolve this problem? I tried to modify the "distributionUrl=https\://services.gradle.org/distributions/gradle-2.2-all.zip" to 4.1 version in `gradle-wrapper.properties` since I use android 3 and it requires the gradle version at least be 4.1.

**Comment by savked** [comment]
@11510746 Try using `distributionUrl=https\://services.gradle.org/distributions/gradle-4.4-all.zip`

**Comment by 11510746** [comment]
> @11510746 Try using `distributionUrl=https\://services.gradle.org/distributions/gradle-4.4-all.zip`

Thanks. But it causes another problem which is mentioned in [#90](https://github.com/avjinder/Minimal-Todo/issues/90)
