### ISSUE TITLE
Error opening in android studio

### ISSUE THREAD

**Issue by kshitij-99** [avjinder/Minimal-Todo#90]
Version 2.2 is required. Current version is 4.4. When i fix this gradle version becomes 2.2 but then google() cant find method for arguements[].

**Comment by walid-al-ashik** [comment]
I'm facing same problem

**Comment by walid-al-ashik** [comment]
yeah..I just figured it out few minutes ago :) from applying this
 
Goto File->Project Structure->Project and update
Change GradleVersion to 4.4 and
AndroidPluginVersion to 3.1.2

**Comment by kshitij-99** [comment]
All the best bro !! Feel free to contact me anytime you got into trouble.

**Comment by walid-al-ashik** [comment]
thank you so much for your support. You're amazing

**Comment by smoralb** [comment]
@kshitij-99 if the issue is solved, please closed the issue. Thanks!!
